/**
 * Synonym Recognition Service - Intelligent synonym matching for companies and financial terms
 * 
 * This service provides:
 * - Company name normalization and synonym matching
 * - Financial term recognition with domain-specific synonyms
 * - Fuzzy matching with phonetic similarity
 * - Contextual synonym suggestions
 * - Real-time synonym learning and adaptation
 */

import {
  SynonymIndex,
  CompanyMatch,
  TermMatch,
  CellReference,
  EnhancedDataType
} from '../types/enhanced-intelligence';

export interface SynonymMatchResult {
  originalTerm: string;
  normalizedTerm: string;
  matchedSynonyms: string[];
  confidence: number;
  matchType: 'exact' | 'fuzzy' | 'phonetic' | 'contextual';
  suggestions: string[];
}

export interface CompanyRecognitionResult {
  companyName: string;
  normalizedName: string;
  stockSymbol?: string;
  aliases: string[];
  confidence: number;
  industry?: string;
  metadata: Record<string, any>;
}

export interface FinancialTermResult {
  term: string;
  category: string;
  definition?: string;
  synonyms: string[];
  relatedTerms: string[];
  confidence: number;
  context: string[];
}

export interface SynonymLearningOptions {
  enableLearning?: boolean;
  confidenceThreshold?: number;
  maxSuggestions?: number;
  contextWindow?: number;
}

export class SynonymRecognitionService {
  private static readonly CONFIDENCE_THRESHOLD = 0.7;
  private static readonly MAX_SUGGESTIONS = 10;
  private static readonly CONTEXT_WINDOW = 3;

  // Enhanced company database with more comprehensive mappings
  private static readonly COMPANY_DATABASE = new Map([
    // Technology Companies
    ['apple inc', {
      aliases: ['apple', 'aapl', 'apple computer', 'apple corporation', 'apple computer inc'],
      stockSymbol: 'AAPL',
      industry: 'Technology',
      metadata: { sector: 'Consumer Electronics', founded: 1976 }
    }],
    ['microsoft corporation', {
      aliases: ['microsoft', 'msft', 'microsoft corp', 'ms'],
      stockSymbol: 'MSFT',
      industry: 'Technology',
      metadata: { sector: 'Software', founded: 1975 }
    }],
    ['amazon.com inc', {
      aliases: ['amazon', 'amzn', 'amazon.com', 'amazon inc'],
      stockSymbol: 'AMZN',
      industry: 'Technology',
      metadata: { sector: 'E-commerce', founded: 1994 }
    }],
    ['alphabet inc', {
      aliases: ['google', 'googl', 'alphabet', 'google inc', 'goog'],
      stockSymbol: 'GOOGL',
      industry: 'Technology',
      metadata: { sector: 'Internet Services', founded: 1998 }
    }],
    ['meta platforms inc', {
      aliases: ['facebook', 'meta', 'fb', 'facebook inc', 'meta platforms'],
      stockSymbol: 'META',
      industry: 'Technology',
      metadata: { sector: 'Social Media', founded: 2004 }
    }],
    ['tesla inc', {
      aliases: ['tesla', 'tsla', 'tesla motors', 'tesla motors inc'],
      stockSymbol: 'TSLA',
      industry: 'Automotive',
      metadata: { sector: 'Electric Vehicles', founded: 2003 }
    }],
    
    // Financial Companies
    ['berkshire hathaway inc', {
      aliases: ['berkshire hathaway', 'berkshire', 'brk.a', 'brk.b', 'brka', 'brkb'],
      stockSymbol: 'BRK.A',
      industry: 'Financial',
      metadata: { sector: 'Conglomerate', founded: 1839 }
    }],
    ['jpmorgan chase & co', {
      aliases: ['jpmorgan', 'jp morgan', 'jpm', 'chase', 'jpmorgan chase'],
      stockSymbol: 'JPM',
      industry: 'Financial',
      metadata: { sector: 'Banking', founded: 1799 }
    }],
    ['bank of america corp', {
      aliases: ['bank of america', 'boa', 'bac', 'bofa'],
      stockSymbol: 'BAC',
      industry: 'Financial',
      metadata: { sector: 'Banking', founded: 1904 }
    }],
    
    // Healthcare Companies
    ['johnson & johnson', {
      aliases: ['j&j', 'jnj', 'johnson and johnson'],
      stockSymbol: 'JNJ',
      industry: 'Healthcare',
      metadata: { sector: 'Pharmaceuticals', founded: 1886 }
    }],
    ['pfizer inc', {
      aliases: ['pfizer', 'pfe'],
      stockSymbol: 'PFE',
      industry: 'Healthcare',
      metadata: { sector: 'Pharmaceuticals', founded: 1849 }
    }]
  ]);

  // Enhanced financial terms database with categories and definitions
  private static readonly FINANCIAL_TERMS_DATABASE = new Map([
    // Revenue and Income
    ['revenue', {
      category: 'Income Statement',
      synonyms: ['sales', 'income', 'turnover', 'receipts', 'gross sales', 'top line'],
      definition: 'Total amount of income generated by a company',
      relatedTerms: ['gross revenue', 'net revenue', 'operating revenue']
    }],
    ['profit', {
      category: 'Income Statement',
      synonyms: ['earnings', 'net income', 'surplus', 'gain', 'bottom line', 'net profit'],
      definition: 'Financial gain after deducting expenses from revenue',
      relatedTerms: ['gross profit', 'operating profit', 'pre-tax profit']
    }],
    ['loss', {
      category: 'Income Statement',
      synonyms: ['deficit', 'shortfall', 'negative earnings', 'net loss'],
      definition: 'Financial deficit when expenses exceed revenue',
      relatedTerms: ['operating loss', 'net loss', 'unrealized loss']
    }],
    
    // Balance Sheet Items
    ['assets', {
      category: 'Balance Sheet',
      synonyms: ['holdings', 'property', 'resources', 'capital', 'possessions'],
      definition: 'Resources owned by a company that have economic value',
      relatedTerms: ['current assets', 'fixed assets', 'intangible assets']
    }],
    ['liabilities', {
      category: 'Balance Sheet',
      synonyms: ['debts', 'obligations', 'payables', 'dues'],
      definition: 'Financial obligations or debts owed by a company',
      relatedTerms: ['current liabilities', 'long-term liabilities', 'contingent liabilities']
    }],
    ['equity', {
      category: 'Balance Sheet',
      synonyms: ['ownership', 'shareholders equity', 'net worth', 'book value'],
      definition: 'Ownership interest in a company after deducting liabilities',
      relatedTerms: ['stockholders equity', 'retained earnings', 'paid-in capital']
    }],
    
    // Cash Flow
    ['cash flow', {
      category: 'Cash Flow',
      synonyms: ['cash movement', 'liquidity', 'cash position', 'cash generation'],
      definition: 'Net amount of cash moving in and out of a business',
      relatedTerms: ['operating cash flow', 'free cash flow', 'cash flow from operations']
    }],
    
    // Financial Ratios
    ['roi', {
      category: 'Financial Ratios',
      synonyms: ['return on investment', 'profitability ratio', 'investment return'],
      definition: 'Measure of investment efficiency',
      relatedTerms: ['roa', 'roe', 'roic']
    }],
    ['pe ratio', {
      category: 'Financial Ratios',
      synonyms: ['price earnings ratio', 'price to earnings', 'p/e', 'earnings multiple'],
      definition: 'Ratio of share price to earnings per share',
      relatedTerms: ['peg ratio', 'forward pe', 'trailing pe']
    }],
    ['ebitda', {
      category: 'Financial Metrics',
      synonyms: ['earnings before interest tax depreciation amortization', 'operating earnings'],
      definition: 'Earnings before interest, taxes, depreciation, and amortization',
      relatedTerms: ['ebit', 'operating income', 'adjusted ebitda']
    }],
    
    // Market Metrics
    ['market cap', {
      category: 'Market Metrics',
      synonyms: ['market capitalization', 'market value', 'market worth'],
      definition: 'Total market value of a company\'s shares',
      relatedTerms: ['enterprise value', 'book value', 'market to book ratio']
    }],
    ['dividend', {
      category: 'Equity',
      synonyms: ['payout', 'distribution', 'yield', 'dividend payment'],
      definition: 'Payment made by companies to shareholders',
      relatedTerms: ['dividend yield', 'dividend per share', 'dividend policy']
    }],
    
    // Business Terms
    ['budget', {
      category: 'Planning',
      synonyms: ['allocation', 'funding', 'financial plan', 'appropriation'],
      definition: 'Financial plan for a specific period',
      relatedTerms: ['forecast', 'projection', 'variance analysis']
    }],
    ['forecast', {
      category: 'Planning',
      synonyms: ['projection', 'prediction', 'estimate', 'outlook'],
      definition: 'Prediction of future financial performance',
      relatedTerms: ['budget', 'guidance', 'consensus estimate']
    }]
  ]);

  // Business terms database
  private static readonly BUSINESS_TERMS_DATABASE = new Map([
    ['customer', {
      category: 'Sales',
      synonyms: ['client', 'buyer', 'consumer', 'patron', 'purchaser'],
      definition: 'Person or organization that buys goods or services',
      relatedTerms: ['prospect', 'lead', 'account']
    }],
    ['vendor', {
      category: 'Procurement',
      synonyms: ['supplier', 'provider', 'contractor', 'seller'],
      definition: 'Company that provides goods or services',
      relatedTerms: ['partner', 'distributor', 'reseller']
    }],
    ['employee', {
      category: 'Human Resources',
      synonyms: ['staff', 'worker', 'personnel', 'team member', 'associate'],
      definition: 'Person working for a company',
      relatedTerms: ['contractor', 'consultant', 'intern']
    }],
    ['department', {
      category: 'Organization',
      synonyms: ['division', 'unit', 'section', 'group', 'team'],
      definition: 'Organizational unit within a company',
      relatedTerms: ['business unit', 'function', 'vertical']
    }]
  ]);

  /**
   * Recognize and match company names with synonyms
   */
  public static recognizeCompany(
    companyName: string,
    options: SynonymLearningOptions = {}
  ): CompanyRecognitionResult | null {
    const normalizedInput = this.normalizeCompanyName(companyName);
    
    // Direct match
    const directMatch = this.COMPANY_DATABASE.get(normalizedInput);
    if (directMatch) {
      return {
        companyName,
        normalizedName: normalizedInput,
        stockSymbol: directMatch.stockSymbol,
        aliases: directMatch.aliases,
        confidence: 1.0,
        industry: directMatch.industry,
        metadata: directMatch.metadata
      };
    }

    // Fuzzy matching through aliases
    for (const [canonicalName, data] of this.COMPANY_DATABASE) {
      const allNames = [canonicalName, ...data.aliases];
      
      for (const alias of allNames) {
        const similarity = this.calculateStringSimilarity(normalizedInput, alias.toLowerCase());
        if (similarity >= (options.confidenceThreshold || this.CONFIDENCE_THRESHOLD)) {
          return {
            companyName,
            normalizedName: canonicalName,
            stockSymbol: data.stockSymbol,
            aliases: data.aliases,
            confidence: similarity,
            industry: data.industry,
            metadata: data.metadata
          };
        }
      }
    }

    // Partial matching for complex company names
    const partialMatch = this.findPartialCompanyMatch(normalizedInput);
    if (partialMatch) {
      return partialMatch;
    }

    return null;
  }

  /**
   * Recognize financial terms and their synonyms
   */
  public static recognizeFinancialTerm(
    term: string,
    context: string[] = [],
    options: SynonymLearningOptions = {}
  ): FinancialTermResult | null {
    const normalizedTerm = term.toLowerCase().trim();
    
    // Direct match
    const directMatch = this.FINANCIAL_TERMS_DATABASE.get(normalizedTerm);
    if (directMatch) {
      return {
        term: normalizedTerm,
        category: directMatch.category,
        definition: directMatch.definition,
        synonyms: directMatch.synonyms,
        relatedTerms: directMatch.relatedTerms,
        confidence: 1.0,
        context
      };
    }

    // Synonym matching
    for (const [canonicalTerm, data] of this.FINANCIAL_TERMS_DATABASE) {
      if (data.synonyms.some(synonym => 
        this.calculateStringSimilarity(normalizedTerm, synonym.toLowerCase()) >= 
        (options.confidenceThreshold || this.CONFIDENCE_THRESHOLD)
      )) {
        const bestMatch = data.synonyms.find(synonym => 
          synonym.toLowerCase().includes(normalizedTerm) || 
          normalizedTerm.includes(synonym.toLowerCase())
        );
        
        if (bestMatch) {
          return {
            term: canonicalTerm,
            category: data.category,
            definition: data.definition,
            synonyms: data.synonyms,
            relatedTerms: data.relatedTerms,
            confidence: 0.8,
            context
          };
        }
      }
    }

    // Contextual matching
    const contextualMatch = this.findContextualFinancialMatch(normalizedTerm, context);
    if (contextualMatch) {
      return contextualMatch;
    }

    return null;
  }

  /**
   * Find synonyms for any term with fuzzy matching
   */
  public static findSynonyms(
    term: string,
    dataType: EnhancedDataType,
    options: SynonymLearningOptions = {}
  ): SynonymMatchResult | null {
    const normalizedTerm = term.toLowerCase().trim();
    const maxSuggestions = options.maxSuggestions || this.MAX_SUGGESTIONS;

    let matchedSynonyms: string[] = [];
    let confidence = 0;
    let matchType: 'exact' | 'fuzzy' | 'phonetic' | 'contextual' = 'exact';
    let suggestions: string[] = [];

    // Company name synonyms
    if (dataType === EnhancedDataType.COMPANY_NAME) {
      const companyMatch = this.recognizeCompany(term, options);
      if (companyMatch) {
        matchedSynonyms = companyMatch.aliases;
        confidence = companyMatch.confidence;
        matchType = confidence === 1.0 ? 'exact' : 'fuzzy';
        suggestions = this.generateCompanySuggestions(normalizedTerm, maxSuggestions);
      }
    }

    // Financial term synonyms
    else if (this.isFinancialDataType(dataType)) {
      const financialMatch = this.recognizeFinancialTerm(term);
      if (financialMatch) {
        matchedSynonyms = financialMatch.synonyms;
        confidence = financialMatch.confidence;
        matchType = confidence === 1.0 ? 'exact' : 'fuzzy';
        suggestions = this.generateFinancialSuggestions(normalizedTerm, maxSuggestions);
      }
    }

    // Business term synonyms
    else {
      const businessMatch = this.recognizeBusinessTerm(term);
      if (businessMatch) {
        matchedSynonyms = businessMatch.synonyms;
        confidence = businessMatch.confidence;
        matchType = confidence === 1.0 ? 'exact' : 'fuzzy';
        suggestions = this.generateBusinessSuggestions(normalizedTerm, maxSuggestions);
      }
    }

    // Phonetic matching as fallback
    if (matchedSynonyms.length === 0) {
      const phoneticMatches = this.findPhoneticMatches(normalizedTerm, dataType);
      if (phoneticMatches.length > 0) {
        matchedSynonyms = phoneticMatches;
        confidence = 0.6;
        matchType = 'phonetic';
      }
    }

    if (matchedSynonyms.length > 0 || suggestions.length > 0) {
      return {
        originalTerm: term,
        normalizedTerm,
        matchedSynonyms,
        confidence,
        matchType,
        suggestions
      };
    }

    return null;
  }

  /**
   * Build comprehensive synonym index
   */
  public static buildSynonymIndex(): SynonymIndex {
    const companyNames = new Map<string, string[]>();
    const financialTerms = new Map<string, string[]>();
    const businessTerms = new Map<string, string[]>();
    const technicalTerms = new Map<string, string[]>();
    const abbreviations = new Map<string, string>();

    // Build company names index
    this.COMPANY_DATABASE.forEach((data, canonicalName) => {
      companyNames.set(canonicalName, data.aliases);
      
      // Add stock symbol mapping
      if (data.stockSymbol) {
        abbreviations.set(data.stockSymbol.toLowerCase(), canonicalName);
      }
    });

    // Build financial terms index
    this.FINANCIAL_TERMS_DATABASE.forEach((data, canonicalTerm) => {
      financialTerms.set(canonicalTerm, data.synonyms);
    });

    // Build business terms index
    this.BUSINESS_TERMS_DATABASE.forEach((data, canonicalTerm) => {
      businessTerms.set(canonicalTerm, data.synonyms);
    });

    // Add common abbreviations
    const commonAbbreviations = new Map([
      ['roi', 'return on investment'],
      ['kpi', 'key performance indicator'],
      ['ceo', 'chief executive officer'],
      ['cfo', 'chief financial officer'],
      ['coo', 'chief operating officer'],
      ['hr', 'human resources'],
      ['it', 'information technology'],
      ['r&d', 'research and development'],
      ['p&l', 'profit and loss'],
      ['b2b', 'business to business'],
      ['b2c', 'business to consumer'],
      ['crm', 'customer relationship management'],
      ['erp', 'enterprise resource planning'],
      ['sla', 'service level agreement'],
      ['api', 'application programming interface']
    ]);

    commonAbbreviations.forEach((expansion, abbrev) => {
      abbreviations.set(abbrev, expansion);
    });

    return {
      companyNames,
      financialTerms,
      businessTerms,
      technicalTerms,
      abbreviations
    };
  }

  /**
   * Learn new synonyms from context
   */
  public static learnSynonymsFromContext(
    cellReferences: CellReference[],
    options: SynonymLearningOptions = {}
  ): Map<string, string[]> {
    const learnedSynonyms = new Map<string, string[]>();
    const contextWindow = options.contextWindow || this.CONTEXT_WINDOW;

    // Group cell references by proximity
    const proximityGroups = this.groupByProximity(cellReferences, contextWindow);

    proximityGroups.forEach(group => {
      const terms = group.map(ref => String(ref.value).toLowerCase().trim());
      const potentialSynonyms = this.identifyPotentialSynonyms(terms);
      
      potentialSynonyms.forEach((synonyms, mainTerm) => {
        if (synonyms.length > 0) {
          learnedSynonyms.set(mainTerm, synonyms);
        }
      });
    });

    return learnedSynonyms;
  }

  // Private helper methods

  private static normalizeCompanyName(name: string): string {
    return name.toLowerCase()
      .replace(/\b(inc|corp|corporation|ltd|limited|llc|co|company)\b\.?/g, '')
      .replace(/[^\w\s]/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();
  }

  private static findPartialCompanyMatch(normalizedName: string): CompanyRecognitionResult | null {
    const words = normalizedName.split(' ').filter(word => word.length > 2);
    
    for (const [canonicalName, data] of this.COMPANY_DATABASE) {
      const canonicalWords = canonicalName.split(' ');
      const matchingWords = words.filter(word => 
        canonicalWords.some(canonicalWord => 
          canonicalWord.includes(word) || word.includes(canonicalWord)
        )
      );

      if (matchingWords.length >= Math.min(2, words.length)) {
        const confidence = matchingWords.length / Math.max(words.length, canonicalWords.length);
        if (confidence >= 0.5) {
          return {
            companyName: normalizedName,
            normalizedName: canonicalName,
            stockSymbol: data.stockSymbol,
            aliases: data.aliases,
            confidence,
            industry: data.industry,
            metadata: data.metadata
          };
        }
      }
    }

    return null;
  }

  private static findContextualFinancialMatch(
    term: string,
    context: string[]
  ): FinancialTermResult | null {
    // Look for contextual clues in surrounding text
    const contextText = context.join(' ').toLowerCase();
    
    // Check if context suggests financial meaning
    const financialIndicators = [
      'financial', 'accounting', 'budget', 'revenue', 'profit', 'loss',
      'balance sheet', 'income statement', 'cash flow', 'ratio', 'analysis'
    ];

    const hasFinancialContext = financialIndicators.some(indicator => 
      contextText.includes(indicator)
    );

    if (hasFinancialContext) {
      // Try partial matching with financial terms
      for (const [canonicalTerm, data] of this.FINANCIAL_TERMS_DATABASE) {
        if (canonicalTerm.includes(term) || term.includes(canonicalTerm)) {
          return {
            term: canonicalTerm,
            category: data.category,
            definition: data.definition,
            synonyms: data.synonyms,
            relatedTerms: data.relatedTerms,
            confidence: 0.6,
            context
          };
        }
      }
    }

    return null;
  }

  private static recognizeBusinessTerm(term: string): {
    synonyms: string[];
    confidence: number;
  } | null {
    const normalizedTerm = term.toLowerCase().trim();
    
    const directMatch = this.BUSINESS_TERMS_DATABASE.get(normalizedTerm);
    if (directMatch) {
      return {
        synonyms: directMatch.synonyms,
        confidence: 1.0
      };
    }

    // Synonym matching
    for (const [, data] of this.BUSINESS_TERMS_DATABASE) {
      if (data.synonyms.some(synonym => 
        this.calculateStringSimilarity(normalizedTerm, synonym.toLowerCase()) >= this.CONFIDENCE_THRESHOLD
      )) {
        return {
          synonyms: data.synonyms,
          confidence: 0.8
        };
      }
    }

    return null;
  }

  private static isFinancialDataType(dataType: EnhancedDataType): boolean {
    return [
      EnhancedDataType.CURRENCY,
      EnhancedDataType.PERCENTAGE,
      EnhancedDataType.NUMBER,
      EnhancedDataType.DECIMAL
    ].includes(dataType);
  }

  private static findPhoneticMatches(term: string, dataType: EnhancedDataType): string[] {
    const phoneticKey = this.generatePhoneticKey(term);
    const matches: string[] = [];

    // Check against company names
    if (dataType === EnhancedDataType.COMPANY_NAME) {
      this.COMPANY_DATABASE.forEach((data, canonicalName) => {
        const allNames = [canonicalName, ...data.aliases];
        allNames.forEach(name => {
          if (this.generatePhoneticKey(name) === phoneticKey) {
            matches.push(name);
          }
        });
      });
    }

    // Check against financial terms
    else if (this.isFinancialDataType(dataType)) {
      this.FINANCIAL_TERMS_DATABASE.forEach((data, canonicalTerm) => {
        const allTerms = [canonicalTerm, ...data.synonyms];
        allTerms.forEach(financialTerm => {
          if (this.generatePhoneticKey(financialTerm) === phoneticKey) {
            matches.push(financialTerm);
          }
        });
      });
    }

    return matches.slice(0, 5); // Limit to top 5 matches
  }

  private static generateCompanySuggestions(term: string, maxSuggestions: number): string[] {
    const suggestions: Array<{ name: string; similarity: number }> = [];

    this.COMPANY_DATABASE.forEach((data, canonicalName) => {
      const allNames = [canonicalName, ...data.aliases];
      allNames.forEach(name => {
        const similarity = this.calculateStringSimilarity(term, name.toLowerCase());
        if (similarity > 0.3 && similarity < this.CONFIDENCE_THRESHOLD) {
          suggestions.push({ name, similarity });
        }
      });
    });

    return suggestions
      .sort((a, b) => b.similarity - a.similarity)
      .slice(0, maxSuggestions)
      .map(s => s.name);
  }

  private static generateFinancialSuggestions(term: string, maxSuggestions: number): string[] {
    const suggestions: Array<{ term: string; similarity: number }> = [];

    this.FINANCIAL_TERMS_DATABASE.forEach((data, canonicalTerm) => {
      const allTerms = [canonicalTerm, ...data.synonyms];
      allTerms.forEach(financialTerm => {
        const similarity = this.calculateStringSimilarity(term, financialTerm.toLowerCase());
        if (similarity > 0.3 && similarity < this.CONFIDENCE_THRESHOLD) {
          suggestions.push({ term: financialTerm, similarity });
        }
      });
    });

    return suggestions
      .sort((a, b) => b.similarity - a.similarity)
      .slice(0, maxSuggestions)
      .map(s => s.term);
  }

  private static generateBusinessSuggestions(term: string, maxSuggestions: number): string[] {
    const suggestions: Array<{ term: string; similarity: number }> = [];

    this.BUSINESS_TERMS_DATABASE.forEach((data, canonicalTerm) => {
      const allTerms = [canonicalTerm, ...data.synonyms];
      allTerms.forEach(businessTerm => {
        const similarity = this.calculateStringSimilarity(term, businessTerm.toLowerCase());
        if (similarity > 0.3 && similarity < this.CONFIDENCE_THRESHOLD) {
          suggestions.push({ term: businessTerm, similarity });
        }
      });
    });

    return suggestions
      .sort((a, b) => b.similarity - a.similarity)
      .slice(0, maxSuggestions)
      .map(s => s.term);
  }

  private static groupByProximity(
    cellReferences: CellReference[],
    contextWindow: number
  ): CellReference[][] {
    const groups: CellReference[][] = [];
    const processed = new Set<string>();

    cellReferences.forEach(ref => {
      const key = `${ref.sheet}:${ref.row}:${ref.col}`;
      if (processed.has(key)) return;

      const group = [ref];
      processed.add(key);

      // Find nearby cells
      cellReferences.forEach(otherRef => {
        const otherKey = `${otherRef.sheet}:${otherRef.row}:${otherRef.col}`;
        if (processed.has(otherKey) || ref.sheet !== otherRef.sheet) return;

        const rowDistance = Math.abs(ref.row - otherRef.row);
        const colDistance = Math.abs(ref.col - otherRef.col);

        if (rowDistance <= contextWindow && colDistance <= contextWindow) {
          group.push(otherRef);
          processed.add(otherKey);
        }
      });

      if (group.length > 1) {
        groups.push(group);
      }
    });

    return groups;
  }

  private static identifyPotentialSynonyms(terms: string[]): Map<string, string[]> {
    const synonymGroups = new Map<string, string[]>();
    
    // Simple heuristic: terms that appear in similar contexts might be synonyms
    // This is a basic implementation - in practice, you'd use more sophisticated NLP
    
    const uniqueTerms = [...new Set(terms)];
    
    for (let i = 0; i < uniqueTerms.length; i++) {
      for (let j = i + 1; j < uniqueTerms.length; j++) {
        const term1 = uniqueTerms[i];
        const term2 = uniqueTerms[j];
        
        // Check if terms are similar enough to be potential synonyms
        const similarity = this.calculateStringSimilarity(term1, term2);
        if (similarity > 0.6 && similarity < 0.95) { // Similar but not identical
          if (!synonymGroups.has(term1)) {
            synonymGroups.set(term1, []);
          }
          synonymGroups.get(term1)!.push(term2);
        }
      }
    }

    return synonymGroups;
  }

  private static calculateStringSimilarity(str1: string, str2: string): number {
    // Levenshtein distance-based similarity
    const matrix: number[][] = [];
    const len1 = str1.length;
    const len2 = str2.length;

    if (len1 === 0) return len2 === 0 ? 1 : 0;
    if (len2 === 0) return 0;

    // Initialize matrix
    for (let i = 0; i <= len1; i++) {
      matrix[i] = [i];
    }
    for (let j = 0; j <= len2; j++) {
      matrix[0][j] = j;
    }

    // Fill matrix
    for (let i = 1; i <= len1; i++) {
      for (let j = 1; j <= len2; j++) {
        const cost = str1[i - 1] === str2[j - 1] ? 0 : 1;
        matrix[i][j] = Math.min(
          matrix[i - 1][j] + 1,      // deletion
          matrix[i][j - 1] + 1,      // insertion
          matrix[i - 1][j - 1] + cost // substitution
        );
      }
    }

    const maxLen = Math.max(len1, len2);
    return (maxLen - matrix[len1][len2]) / maxLen;
  }

  private static generatePhoneticKey(value: string): string {
    // Simple phonetic key generation (Soundex-like)
    return value.toLowerCase()
      .replace(/[aeiou]/g, '')
      .replace(/[^a-z]/g, '')
      .substring(0, 4)
      .padEnd(4, '0');
  }
}